// ============================================================
// KANAPUTZ OBSERVATORY — Content Data (v10 Wave-Tagged)
// ============================================================
// 6 waves. 30 terminal sightings (5+8+5+5+7).
// WaveSystem.getVisibleContent(array) filters by current wave.

// ===== TERMINAL SIGHTINGS (30 entries across 5 content waves) =====
const SIGHTINGS = [
  // ----- WAVE 1 (5): Global sightings, type designations only, no community names -----
  { wave: 1, date: '2024-09-03', time: '22:14:33', location: 'SHI-07 / TAIPEI-TW', observer: 'R-01', type: 'Type 1', description: 'First confirmed visual. Small specimen moved at impossible speed across Shilin Night Market entrance. Stopped abruptly at flower stall. Remained motionless 47 sec observing potted orchid. Then vanished.' },
  { wave: 1, date: '2024-09-12', time: '01:23:08', location: 'MUM-02 / MUMBAI-IN', observer: 'R-19', type: 'Type 4', description: 'Large-mouthed specimen detected near arguing couple outside train station. Opened mouth wide — appeared to inhale surrounding atmosphere. Couple stopped arguing within 12 sec. Specimen visibly inflated to approx 1.5x resting volume. Waddled away.' },
  { wave: 1, date: '2024-09-18', time: '23:55:17', location: 'LON-05 / LONDON-UK', observer: 'R-31', type: 'Type 2', description: 'Specimen raised arms dramatically, extended tongue, performed aggressive hip display toward two arguing pedestrians. Neither pedestrian alarmed. Both laughing within 4 sec. Specimen continued display for 20 sec after conflict resolved.' },
  { wave: 1, date: '2024-09-25', time: '02:07:44', location: 'TOK-08 / TOKYO-JP', observer: 'R-09', type: 'Type 3', description: 'Rhythmic movement detected. Tall specimen swaying near market music speaker. Tail displacement knocked over three stalls. Specimen appeared unaware of damage. Vendors laughing.' },
  { wave: 1, date: '2024-11-03', time: '02:58:16', location: 'NYC-07 / NEW YORK-US', observer: 'R-31', type: null, description: 'Multiple specimens detected within 200m radius. All four types present simultaneously — first documented co-occurrence. Duration: 4 min 22 sec. All specimens moved in same direction before dispersing.' },

  // ----- WAVE 2 (8): Community names leak in, personality, global spread -----
  { wave: 2, date: '2024-10-02', time: '04:18:55', location: 'BKK-03 / BANGKOK-TH', observer: 'R-27', type: 'Type 1', description: 'Specimen performed perimeter patrol of children\'s playground. Zigzag pattern, stopping every 3-4m. One child approached — specimen froze, body softened visibly. Tiny smile observed. Child giggled. Specimen resumed patrol.' },
  { wave: 2, date: '2024-10-18', time: '23:12:09', location: 'SHI-05 / TAIPEI-TW', observer: 'R-07', type: 'Type 2', description: 'Specimen locally called "MrQ" attempted to intimidate a street cat. Arms raised, tongue extended, hips shaking. Cat unimpressed. Specimen escalated — performed headbutt charge at trash can. Got dizzy. Flexed proudly.' },
  { wave: 2, date: '2024-10-25', time: '01:45:33', location: 'BER-03 / BERLIN-DE', observer: 'R-22', type: 'Type 3', description: 'Community designation "Groovix." Detected subway busker playing guitar. Began involuntary rhythm sway. Full-body movement escalated within 30 sec. Tail swept umbrella stand into the street. Busker incorporated chaos into performance. Crowd doubled.' },
  { wave: 2, date: '2024-11-10', time: '03:53:08', location: 'SHI-11 / TAIPEI-TW', observer: 'R-14', type: 'Type 4', description: 'Specimen locally known as "Muncha" — inflation event near arguing couple. Approx 2x volume. Deflation took 45 sec.' },
  { wave: 2, date: '2024-11-28', time: '01:22:14', location: 'NYC-07 / NEW YORK-US', observer: 'R-31', type: 'Type 1', description: 'Specimen identified as community "Fugu" — sprint-to-tenderness cycle confirmed. Explosive sprint down platform, sudden freeze at sight of sleeping kitten near ventilation grate. Full tender pause: 62 sec.' },
  { wave: 2, date: '2024-12-03', time: '23:09:37', location: 'PAR-12 / PARIS-FR', observer: 'R-18', type: 'Type 3', description: 'Montmartre sighting. Groovix-type detected near accordion player. Rhythm drift escalated to full-body groove. Tail whipped through three easels. Artists seemed delighted rather than upset.' },
  { wave: 2, date: '2024-12-18', time: '00:55:21', location: 'SHI-03 / TAIPEI-TW', observer: 'R-14', type: 'Type 2', description: 'MrQ confronted group of teenagers playing loud music. Performed concert mode: jumping, arm-waving, butt-shaking. Started involuntary crowd wave among teenagers. All parties laughing within 15 sec.' },
  { wave: 2, date: '2024-12-22', time: '03:17:42', location: 'BKK-05 / BANGKOK-TH', observer: 'R-27', type: 'Type 1', description: 'Chatuchak Market. Fugu-type detected near spice vendor. Sprint-freeze pattern: 4 cycles in 3 min. Each freeze oriented toward different small detail — dewdrop on chili pepper, butterfly resting on ginger root.' },

  // ----- WAVE 3 (5): Energy loss dominant, diminished flags, alarm -----
  { wave: 3, date: '2025-01-05', time: '02:33:49', location: 'SHI-14 / TAIPEI-TW', observer: 'R-01', type: 'Type 4', description: 'Muncha positioned near hospital entrance. Antennae vibrating continuously. Absorbed ambient emotional weight for 8 min — longest recorded session. Inflation gradual, reaching 3x resting volume. ENERGY STATUS: DIMINISHED — slow deflation, squeaking sounds weak. Something is costing them.' },
  { wave: 3, date: '2025-01-12', time: '04:07:29', location: 'NYC-07 / NEW YORK-US', observer: 'R-31', type: 'Type 1', description: 'Fugu sprint-to-tenderness cycle. ENERGY STATUS: DIMINISHED — sprint speed measurably slower than September baseline. Tender pauses shorter: 14 sec avg vs 22 sec. They moved differently when they left.' },
  { wave: 3, date: '2025-01-18', time: '01:14:55', location: 'SEL-04 / SEOUL-KR', observer: 'R-12', type: 'Type 4', description: 'Muncha positioned between stressed office worker and vending machine. Antennae vibrating. Absorbed what appeared to be ambient frustration. Inflated 2x. ENERGY STATUS: DIMINISHED — deflation took 90 sec vs 30 sec baseline. Worker relaxed. Specimen did not.' },
  { wave: 3, date: '2025-01-25', time: '23:12:09', location: 'SHI-05 / TAIPEI-TW', observer: 'R-07', type: 'Type 2', description: 'MrQ display intensity declining. Performance duration: 20 sec vs 45 sec norm. ENERGY STATUS: DIMINISHED — theatrical posture less exaggerated. Headbutt charge slower. Flexed, but dimmer.' },
  { wave: 3, date: '2025-02-01', time: '22:07:33', location: 'SHI-14 / TAIPEI-TW', observer: 'R-07', type: null, description: 'Four-type convergence event #7. Duration: 18 min — longest recorded. Fugu trembling. MrQ silent — first recorded non-performance. Groovix swaying without visible rhythm. Muncha deflated, still, antennae flat. Something was different.' },

  // ----- WAVE 4 (5): Convergence confirmed, Shilin concentration -----
  { wave: 4, date: '2025-02-10', time: '01:14:55', location: 'SHI-25 / TAIPEI-TW', observer: 'R-01', type: 'Type 1', description: 'Followed Fugu-type for 3 hours. Alternated between explosive sprints and complete stillness. Led to location outside Shilin district boundaries. [COORDINATES REDACTED]. Specimen oriented toward fixed point for 4 min 11 sec.' },
  { wave: 4, date: '2025-02-15', time: '02:38:17', location: 'SHI-07 / TAIPEI-TW', observer: 'R-14', type: null, description: 'All four types observed within 50m radius. Duration increasing: 12 min 44 sec. All oriented in same direction during final 3 min. Direction consistent with previous convergence events.' },
  { wave: 4, date: '2025-02-20', time: '23:45:33', location: 'TPE-01 / TAIPEI-TW', observer: 'R-01', type: null, description: 'UV analysis of Shilin receipts confirms residual energy signatures at 7 of 12 documented sighting locations. Pattern is radial. Center point calculations underway.' },
  { wave: 4, date: '2025-02-25', time: '03:28:51', location: 'SHI-30 / TAIPEI-TW', observer: 'R-14', type: 'Type 3', description: 'Groovix performing sustained rhythmic movement without external music. Duration: 7 min. Tail movements traced figure-eight pattern. Ground vibration measurable at 15m. Three nearby specimens appeared to respond — all oriented toward Groovix position.' },
  { wave: 4, date: '2025-03-01', time: '01:55:08', location: 'JIU-02 / JIUFEN-TW', observer: 'R-01', type: 'Type 1', description: 'Jiufen Old Street. Fugu-type sprinted from Shilin to Jiufen — 30km in estimated 4 min. Stopped at temple steps. Tender pause: 3 min 47 sec. Longest recorded. Oriented toward ocean.' },

  // ----- WAVE 5 (7): Source proximity, anomalies hiding safe code 3-17-58 -----
  { wave: 5, date: '2025-03-05', time: '02:44:19', location: 'SRC-01 / ??????-TW', observer: 'R-01', type: null, description: 'Source detector activated. Initial reading: coherence 34%. Fluctuating. M. says the readings are correct.' },
  { wave: 5, date: '2025-03-08', time: '04:11:55', location: 'SHI-07 / TAIPEI-TW', observer: 'R-14', type: 'Type 1', description: 'Fugu sprint frequency doubled in 72 hours. Route patterns increasingly direct — fewer zigzags, longer stillness. Tender pauses now oriented exclusively toward Source bearing.' },
  { wave: 5, date: '2025-03-10', time: '04:02:48', location: '03-17-58 / ??????-??', observer: '---', type: '-------', description: '%%SIGNAL ANOMALY. COORDINATES DO NOT RESOLVE. ENTRY FLAGGED.%%', isAnomaly: true },
  { wave: 5, date: '2025-03-12', time: '01:55:44', location: 'SHI-ALL / TAIPEI-TW', observer: 'R-01', type: null, description: '14 specimens detected simultaneously across Shilin. All types. All moving toward same external point. Source detector: coherence 67%.' },
  { wave: 5, date: '2025-03-15', time: '00:42:31', location: 'SRC-01 / ??????-TW', observer: 'R-01', type: null, description: 'Source coherence: 58%. Steady increase. Crystal responds to convergence — spikes +12-15%. M. suggests the relationship is bidirectional.' },
  { wave: 5, date: '2025-03-17', time: '23:28:44', location: 'LOC: 03-17-58', observer: '???', type: null, description: '%%DATA CORRUPTION — TIMESTAMP MISMATCH — COORDINATES ECHO PREVIOUS ANOMALY — FLAGGED FOR REVIEW%%', isAnomaly: true },
  { wave: 5, date: '2025-03-18', time: '04:22:07', location: 'SRC-01 / ??????-TW', observer: 'R-01', type: null, description: 'Crystal responding to ambient conditions without specimen proximity. Self-sustaining? M.: "It remembers." Coherence: 71%.' },
];

// ===== MAP DOTS =====
const MAP_SIGHTINGS = [
  { id: 0, wave: 1, city: 'Bangkok', location: 'Chatuchak Market', left: '72%', top: '48%', description: 'Type 1 detected near spice vendor. Sprint-freeze cycle: 4 repetitions.', hasFootage: false, evidenceType: 'visual' },
  { id: 1, wave: 1, city: 'Berlin', location: 'U-Bahn Alexanderplatz', left: '50%', top: '34%', description: 'Type 3 rhythmic anomaly. Three commuters displaced by tail.', hasFootage: false, evidenceType: 'behavioral' },
  { id: 2, wave: 1, city: 'Tokyo', location: 'Shibuya Crossing', left: '80%', top: '40%', description: 'Type 2 theatrical display during rush hour. Universal laughter.', hasFootage: false, evidenceType: 'visual' },
  { id: 3, wave: 1, city: 'Paris', location: 'Montmartre', left: '48%', top: '34%', description: 'Type 3 near accordion player. Three easels destroyed.', hasFootage: false, evidenceType: 'behavioral' },
  { id: 4, wave: 1, city: 'New York', location: 'Subway Tunnel B-7', left: '29%', top: '35%', description: 'Type 1 sprint-to-tenderness. 62 sec pause at sleeping kitten.', hasFootage: false, evidenceType: 'visual' },
  { id: 5, wave: 2, city: 'Mumbai', location: 'Train Station District', left: '65%', top: '47%', description: 'Type 4 tension absorption event. Couple stopped arguing within 12 sec.', hasFootage: false, evidenceType: 'behavioral' },
  { id: 6, wave: 2, city: 'London', location: 'Southbank', left: '47%', top: '33%', description: 'Type 2 aggressive hip display. Both pedestrians laughing within 4 sec.', hasFootage: false, evidenceType: 'visual' },
  { id: 7, wave: 2, city: 'Seoul', location: 'Gangnam Station', left: '79%', top: '39%', description: 'Type 4 absorbed ambient frustration near vending machine. Worker visibly relaxed.', hasFootage: false, evidenceType: 'temporal' },
  { id: 8, wave: 3, city: 'Taipei', location: 'Shilin Night Market', left: '77%', top: '42%', description: 'PRIMARY CLUSTER. All four types. Convergence events increasing. ENERGY STATUS: DIMINISHED across all types.', hasFootage: true, evidenceType: 'source' },
  { id: 9, wave: 4, city: 'Cape Town', location: 'V&A Waterfront', left: '52%', top: '63%', description: 'Type 1 — first Southern Hemisphere sighting. Oriented toward Taipei bearing.', hasFootage: false, evidenceType: 'temporal' },
];

// ===== SHILIN DETAIL MAP DOTS (Wave 4+) =====
const SHILIN_DOTS = [
  { id: 's0', wave: 4, location: 'Shilin Night Market — Main Gate', left: '35%', top: '30%', description: 'Primary convergence node. All four types documented. Highest frequency of multi-type co-occurrence events.', evidenceType: 'behavioral' },
  { id: 's1', wave: 4, location: 'Jiantan MRT Station', left: '25%', top: '22%', description: 'Transit point. Type 1 specimens sprint between station and market in under 3 sec. Route consistent.', evidenceType: 'visual' },
  { id: 's2', wave: 4, location: 'Shilin Residence Park', left: '55%', top: '45%', description: 'Type 3 rhythmic events. Tail displacement damaged two park benches. Groundkeeper unaware of cause.', evidenceType: 'behavioral' },
  { id: 's3', wave: 4, location: 'Wenlin Road Intersection', left: '40%', top: '55%', description: 'Type 4 absorption events concentrated here. Three documented cases of ambient tension reduction.', evidenceType: 'visual' },
  { id: 's4', wave: 4, location: 'Shilin Elementary — Perimeter', left: '60%', top: '35%', description: 'Type 1 perimeter patrol pattern. Multiple tender pauses near playground fence.', evidenceType: 'temporal' },
  { id: 's5', wave: 4, location: 'Zhishan Garden', left: '70%', top: '28%', description: 'Type 2 theatrical display. Duration 45 sec. Three witnesses, all laughing.', evidenceType: 'behavioral' },
  { id: 's6', wave: 4, location: 'Danan Road Market Alley', left: '30%', top: '65%', description: 'Multi-specimen event #4. All types. Duration 8 min 22 sec. All oriented toward same bearing before dispersal.', evidenceType: 'temporal' },
  { id: 's7', wave: 5, location: 'Shilin District — Outer Edge', left: '18%', top: '75%', description: 'Source proximity readings spike. UV residue on pavement. Not a sighting location — an orientation point.', evidenceType: 'source' },
  { id: 'source', wave: 5, location: '[SOURCE LOCATION — COORDINATES WITHHELD]', left: '82%', top: '72%', description: 'Camera shakes. Timestamp anomaly. No visible specimen. Audio contains low, warm hum. Duration: longer than standard clip.', evidenceType: 'source', isSource: true },
];

// ===== JOURNAL PAGES (10 pages, 6 waves) =====
const JOURNAL_PAGES = [
  { wave: 1, page: 1, date: 'September 3', text: 'I have started calling them Kanaputz. I do not know why — the word surfaced and stuck. Something moved through the night market tonight that should not have been possible. A small creature — no larger than a house cat — crossed 40 meters of crowded market lane in under three seconds. Then it stopped. Completely. There was a flower growing through a crack in the pavement and it stood there, perfectly still, looking at it. I could not move either. I need to come back tomorrow.', marginNote: null, contentType: 'text' },
  { wave: 1, page: 2, date: 'November 19', text: 'A different one today. Rounder. Louder in posture, if that makes sense. It performed what I can only describe as a theatrical display of aggression outside my apartment. Arms raised, tongue extended, hips moving. It was not threatening. It was performing. Two neighbors who had been arguing on the landing stopped and watched. They were laughing before it finished.', marginNote: 'Distinct from Sept specimen. Rounder body, different behavior entirely. How many types are there?', contentType: 'text' },
  { wave: 2, page: 3, date: 'October 12', text: 'I am now confident there are four distinct types. Type 1: hyper-alert sprinter with a tender side. Type 2: theatrical performer who thinks it is scaring away problems. Type 3: tall, clumsy, moves to rhythm involuntarily. Cannot control its tail. Type 4: opens its mouth and appears to inhale tension from the air. Inflates visibly. All four share a common trait: they appear to move in the same direction when not engaged in immediate behavior.', marginNote: 'All moving toward something. Every type, every time.', contentType: 'text' },
  { wave: 2, page: 4, date: 'October 29', text: 'Spoke to M. about the pattern. She was not surprised. She said she had felt them before she saw them — "concentrations of intention" was her phrase. Not wandering. Arriving. The locals have started naming them. The Type 4 near the school is "Muncha." It keeps eating whatever is in the air around that intersection.', marginNote: 'M. uses community names naturally. "Fugu stopped mid-sprint and went completely still. Something small had caught his attention."', contentType: 'text' },
  { wave: 3, page: 5, date: 'January 5', text: 'Something is wrong. The specimens are losing energy. Every type shows the same pattern: diminished output. Fugu\'s sprints are slower. MrQ\'s displays are shorter. Groovix\'s rhythm is irregular. Muncha takes twice as long to deflate after absorption. Whatever they take from us, it costs them. I counted seven convergence events this month — all four types, same direction, increasing duration. They are gathering more often but moving less.', marginNote: 'They carry what we cannot hold. It is not free.', contentType: 'text' },
  { wave: 3, page: 6, date: 'January 15', text: 'Called M. She will come to Taipei.', marginNote: null, contentType: 'text' },
  { wave: 4, page: 7, date: 'March 5', text: 'M. arrived yesterday. She walked through the night market without speaking for two hours. When she finally stopped, she said: "They are not scattered. They are arranged." She pointed at locations I had documented. "These are not random encounters," she said. "These are stations on a path that leads somewhere."', marginNote: 'Source detector fluctuating. 34% to 58% in 48 hours. M. says the relationship is bidirectional.', contentType: 'text' },
  { wave: 4, page: 8, date: 'March 14', text: 'Muncha sat at the center today. Not eating. Not inflating. Just present. Antennae extended, mouth closed. The others held a perimeter — thirty meters out, perfectly spaced. They maintained this formation for twenty-two minutes. Nothing happened. Everything happened.', marginNote: 'M. sat with them. After eleven minutes she said: "It remembers." She would not explain.', contentType: 'text' },
  { wave: 5, page: 9, date: 'March 21', text: 'They are all coming. Every documented specimen from every location. The sprint paths, the dance routes, the waddle trajectories — all converging on the same coordinates. Global sightings dropping to zero. The Source coherence hit 73% this morning and the crystal was visible to the naked eye for the first time. Warm light. Steady. Not flickering — breathing.', marginNote: 'The Source does not store data. It stores presence. Every moment a being was fully still near it, the crystal kept that moment. Now it is giving them back.', contentType: 'text' },
  { wave: 6, page: 10, date: 'March 23', text: 'If you are reading this, you have been paying attention. That means you understand enough. The Source is not a fixed location. It is a membrane — a frequency that responds when enough beings choose to be still together. The Kanaputz are not going somewhere. They are showing us how to arrive. The rest you have to see.', marginNote: null, contentType: 'text' }
];

// ===== PINBOARD ITEMS =====
const PINBOARD_ITEMS = [
  // W1: First observations, type designations (4 post-its)
  { wave: 1, type: 'postit', text: 'Night market, 3am — four distinct silhouettes. None matching known fauna.', color: '#f7dc6f', rotation: -2, position: { top: '2%', left: '2%' }, author: 'researcher' },
  { wave: 1, type: 'postit', text: 'The fast one stopped at a flower growing through concrete. Stayed 47 seconds. WHY?', color: '#f1948a', rotation: 3, position: { top: '5%', left: '35%' }, author: 'researcher' },
  { wave: 1, type: 'postit', text: 'Type 4 — mouth takes up 70% of body. Inflates when near arguments. Deflates when they stop.', color: '#82e0aa', rotation: -1, position: { top: '3%', left: '62%' }, author: 'researcher' },
  { wave: 1, type: 'postit', text: 'Every sighting clusters around Shilin. WHY SHILIN?', color: '#85c1e9', rotation: 1, position: { top: '8%', left: '85%' }, author: 'researcher' },

  // W2: Community names, M.'s first notes, sketches (4 post-its)
  { wave: 2, type: 'postit', text: 'They carry what we cannot hold. It is not free.', color: '#f5b7b1', rotation: -2, position: { top: '18%', left: '15%' }, author: 'm' },
  { wave: 2, type: 'postit', text: 'Fugu stopped mid-sprint and went completely still. Something small had caught his attention. He stayed that way for almost a minute.', color: '#f5b7b1', rotation: 1, position: { top: '22%', left: '75%' }, author: 'm' },
  { wave: 2, type: 'sketch', image: 'fugu-sketch-1.png', position: { top: '30%', left: '8%' }, rotation: 2, label: 'Type 1 — "Fugu" — sprint form' },
  { wave: 2, type: 'sketch', image: 'MrQ-sketch-1.png', position: { top: '32%', left: '30%' }, rotation: -3, label: 'Type 2 — "MrQ" — display posture' },
  { wave: 2, type: 'sketch', image: 'groovix-sketch-1.png', position: { top: '55%', left: '10%' }, rotation: -1, label: 'Type 3 — "Groovix" — rhythm posture' },
  { wave: 2, type: 'sketch', image: 'muncha-sketch-1.png', position: { top: '58%', left: '32%' }, rotation: 4, label: 'Type 4 — "Muncha" — inflation state' },
  { wave: 2, type: 'postit', text: 'Berlin, NYC, Paris, Bangkok — they are EVERYWHERE. But they keep coming back to Taipei.', color: '#f7dc6f', rotation: 2, position: { top: '28%', left: '48%' }, author: 'researcher' },
  { wave: 2, type: 'postit', text: 'The locals named them: Fugu, MrQ, Groovix, Muncha. I will continue using type designations.', color: '#82e0aa', rotation: -3, position: { top: '46%', left: '72%' }, author: 'researcher' },

  // W3: Energy loss, alarm (3 post-its)
  { wave: 3, type: 'postit', text: 'Energy output declining across ALL types. What is costing them?', color: '#f1948a', rotation: 1, position: { top: '68%', left: '58%' }, author: 'researcher' },
  { wave: 3, type: 'postit', text: 'MrQ performed for 20 seconds today. Used to be 45. He flexed at the end but it was dimmer.', color: '#f7dc6f', rotation: -3, position: { top: '40%', left: '42%' }, author: 'researcher' },
  { wave: 3, type: 'receipt', position: { top: '62%', left: '55%' }, rotation: 3, vendor: 'SHILIN MARKET STALL #17', date: '2024-11-10', items: ['Tea egg ×2', 'Stinky tofu ×1', '---', 'ANOMALOUS RESIDUE DETECTED'], total: 'NT$ 85' },
  { wave: 3, type: 'photo', image: null, position: { top: '35%', left: '55%' }, rotation: -2, label: 'Shilin Night Market — 02:40', caption: 'Motion blur near flower stall. Fugu?' },
  { wave: 3, type: 'postit', text: 'M.: "Not from here. The cost is the distance."', color: '#f5b7b1', rotation: -2, position: { top: '55%', left: '25%' }, author: 'm' },

  // W4: Convergence confirmed, crystal sketch, diagram (2 post-its)
  { wave: 4, type: 'diagram', position: { top: '20%', left: '68%' }, rotation: -1, title: 'CONVERGENCE VECTORS', description: 'All specimen trajectories — directional arrows all pointing toward Taipei. Radial pattern confirmed. Center: [REDACTED]' },
  { wave: 4, type: 'sketch', image: 'source crystal-1.png', position: { top: '70%', left: '15%' }, rotation: 1, label: 'Source crystal — preliminary sketch' },
  { wave: 4, type: 'postit', text: 'M.: "They are not wandering here. They are arriving."', color: '#f5b7b1', rotation: 3, position: { top: '80%', left: '68%' }, author: 'm' },
  { wave: 4, type: 'postit', text: 'Followed Fugu for 3 hours. Sprint paths no longer random. He knows where he is going.', color: '#85c1e9', rotation: -1, position: { top: '62%', left: '85%' }, author: 'researcher' },
  { wave: 4, type: 'receipt', position: { top: '50%', left: '38%' }, rotation: -4, vendor: '7-ELEVEN SHILIN #229', date: '2025-01-08', items: ['Battery pack ×1', 'Onigiri ×2', '---', 'UV TRACE: POSITIVE'], total: 'NT$ 147' },

  // W5: Source proximity, anomalies (2 post-its)
  { wave: 5, type: 'postit', text: 'the feed hides what the feed cannot say.', color: '#f1948a', rotation: 1, position: { top: '35%', left: '78%' }, author: 'researcher' },
  { wave: 5, type: 'postit', text: 'All observed specimens moving in the same direction. Every type. Every continent.', color: '#85c1e9', rotation: -2, position: { top: '74%', left: '32%' }, author: 'researcher' },
  { wave: 5, type: 'photo', image: null, position: { top: '42%', left: '18%' }, rotation: 2, label: 'Jiufen Old Street — 01:55', caption: 'Temple steps. Type 1 oriented toward ocean.' },

  // W6: After safe (1 post-it)
  { wave: 6, type: 'postit', text: 'M. sat with them. Eleven minutes. Then: "It remembers." Look around you. They are closer than you think.', color: '#f5b7b1', rotation: 2, position: { top: '84%', left: '5%' }, author: 'm' },
];

const PINBOARD_UV = [
  { type: 'arrow', from: { top: '30%', left: '50%' }, to: { top: '70%', left: '20%' }, label: 'PULL' },
  { type: 'note', text: 'All paths converge \u2192 SE bearing 127\u00B0', position: { top: '45%', left: '60%' }, rotation: -5 },
  { type: 'circle', position: { top: '65%', left: '25%' }, radius: '8%', label: 'NON-SHILIN LOCATION' },
  { type: 'note', text: 'Source dot matches. Confirm with M.', position: { top: '72%', left: '45%' }, rotation: 2 },
  { type: 'note', text: '03 . 17 . 58 — check the feed', position: { top: '82%', left: '60%' }, rotation: -3 },
];

// ===== CASSETTE TAPES =====
const CASSETTE_TAPES = [
  { id: 'T-01', wave: 1, requiresSafe: false, label: 'T-01: First Field Recording', description: 'Researcher outdoors, excited. Wind and night market ambience. "It was fast. Impossibly fast. And then it just... stopped. There was a flower growing through a crack in the concrete and it stood there, perfectly still, looking at it. I need to come back tomorrow."', audioUrl: null },
  { id: 'T-02', wave: 2, requiresSafe: false, label: 'T-02: The Cost', description: 'In the field. A Type 4 approaches a street argument. Opens its mouth wide — "It seemed to be inhaling the situation." The argument stops. The creature inflates, then slowly deflates. But the researcher notices something: "It took longer to recover this time. It was dimmer afterward. Whatever it absorbed, it paid for."', audioUrl: null },
  { id: 'T-03', wave: 3, requiresSafe: false, label: 'T-03: The Pattern', description: 'At the desk. "Every sighting. Every type. The sprinter, the performer, the dancer, the eater. They all end the same way — movement in the same direction." First time "Source" is spoken.', audioUrl: null },
  { id: 'T-04', wave: 4, requiresSafe: false, label: 'T-04: [ \u223F ]', description: 'No label. Night ambience: traffic, insects, wind. Then — small sounds underneath. Squeaks, hums, chirps. Rhythmic and warm. Almost playful. The sounds creatures made of joy would make. No narration. Duration: 2 min 41 sec.', audioUrl: null },
  { id: 'T-05', wave: 6, requiresSafe: true, label: 'T-05: The Medium Interview', description: 'M.: "Groovix does not dance because he wants to. The rhythm is in him." She describes them as concentrations of intention. "They are not wandering here. They are arriving." Researcher asks about the Source. Long pause. Then, quieter: "They are not the only ones who came from somewhere else." Mid-word, tape cuts.', audioUrl: null },
];

// ===== SAFE DOSSIER =====
const SAFE_DOSSIER = {
  sections: [
    { title: 'Section 1 — Type Profiles', content: [
      { type: 'Type 1 — Fugu', classification: 'Hyper-alert Sprinter / Perceptive Guardian', text: 'Detects low vibration, danger, and emotional tension before others. Reacts with explosive speed — spine compresses into aerodynamic "bullet mode." Beneath the hyper-vigilance: a profoundly tender heart. When encountering small wonders — a baby smiling, dew on a leaf — stops completely, posture softens, warm expression emerges. Flagship: blink-and-miss-it sprint + tender pause.', footnote: 'Colloquially "Fugu" — name references defensive compression posture.' },
      { type: 'Type 2 — MrQ', classification: 'Theatrical Aggressor / Performer', text: 'Overconfident, dramatic, emotionally reactive. Believes it is scaring away negative energy. Actual function: hyperactive performer. Arms perpetually raised. Glossy head for headbutt charges. Tongue display intended as intimidation consistently produces laughter. Flagship: frantic jumping with arm-shaking + rhythmic hip movement.', footnote: 'Colloquially "MrQ" — references inquisitive head-tilt.' },
      { type: 'Type 3 — Groovix', classification: 'Involuntary Rhythmic Mover / Accidental Destructor', text: 'Tall, gentle, clumsy. Long tail with wide swinging range. Natural rhythm sway even when idle — involuntary nervous system response. Cannot separate emotional state from physical movement. When exposed to rhythm, movement spreads until environmental damage occurs. Flagship: involuntary rhythmic movement escalating to accidental structural damage.', footnote: 'Colloquially "Groovix." Note: specimen never decides to dance. Movement happens to it.' },
      { type: 'Type 4 — Muncha', classification: 'Tension Ingester / Inflation-Deflation Cycle', text: 'Attempts to help by "eating" emotional heaviness. Mouth comprises 70% of body. Two antennae vibrate when detecting ingestible energy. Can inflate to 4x resting volume. Deflation rapid, accompanied by squeaking. Tiny limbs create characteristic waddle. Flagship: tension devouring + visible inflation cycle.', footnote: 'Colloquially "Muncha" — earliest community-named specimen.' }
    ]},
    { title: 'Section 2 — Energy Depletion Analysis', content: 'Specimens that absorb emotional heaviness lose coherence. The more they absorb, the dimmer they become. Prolonged exposure to high-tension environments produces measurable decline in sprint speed (Type 1), display intensity (Type 2), rhythm stability (Type 3), and deflation rate (Type 4).\n\nThey instinctively seek something to restore themselves. Three hypotheses:\n\nHypothesis A (Researcher): Inter-dimensional organisms displaced by energy imbalance. Behaviors are instinctive responses to emotional frequency differentials. They do not intend to help. They react. The energy cost is physical.\n\nHypothesis B (M.): Concentrations of joy — condensed from a world where joy is the baseline. Absorbing our heaviness depletes what they are made of. They need the Source the way we need air.\n\nHypothesis C (Integrated): Both perspectives describe the same phenomenon at different scales. Physically real AND energetically coherent. The distinction may not apply.' },
    { title: 'Section 3 — Convergence Report', content: 'Directional analysis of all documented sighting trajectories.\n\nEvery type. Every location. Every continent. When not engaged in immediate behavioral response, all specimens orient in the same direction. Sprint paths, dance routes, waddle trajectories — bearing 127\u00B0 SE from European observations, adjusted for curvature.\n\nAll roads lead to Shilin. Within Shilin, to one specific location.\n\n\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 coordinates confirmed \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\n\nThe convergence is accelerating. Frequency of multi-type co-occurrence events has increased 340% since January.' },
    { title: 'Section 4 — The Source', content: '\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\n\n...an anchor between their origin and this world...\n\n\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\n\n...the crystal stabilises them...\n\n\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\n\nAll observed specimens appear to be moving in the same direction.\n\n\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588', isRedacted: true },
    { title: 'Section 5 — Incident Report', content: 'CLASSIFIED — Proximity Event\nShilin District — 03:17\n\n\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 approached \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 at coordinates \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588. Duration: \u2588\u2588 minutes. All four types present. \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 readings exceeded \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588.\n\nObserver: "\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588 something I cannot \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588."\n\nConclusion: Observation concluded. Not approached.\n\n[Torn section — bottom third missing]', isRedacted: true }
  ],
  finalPage: 'If you are reading this, you have been paying attention.\nThat means you understand enough.\nThe rest you have to see.'
};

// ===== SOURCE MONITOR =====
const SOURCE_MONITOR = {
  wave5: { coherence: 73, status: 'ACTIVE — CALIBRATING', feed: 'Crystal installation in progress. Coherence baseline establishing. Specimens orienting toward Source bearing.', readings: ['CRYSTAL STATE: RESPONSIVE', 'AMBIENT FREQ: 432.7 Hz', 'CONVERGENCE EVENTS: 7 (last 48h)', 'SPECIMEN PROXIMITY: DETECTED', 'MEMBRANE STABILITY: 67%'] },
  wave6: { coherence: 89, status: 'ACTIVE — STABILIZED', feed: 'Physical convergence confirmed. Crystal luminescence visible without instruments.', readings: ['CRYSTAL STATE: SELF-SUSTAINING', 'AMBIENT FREQ: 528.0 Hz (LOCKED)', 'CONVERGENCE EVENTS: CONTINUOUS', 'SPECIMEN COUNT: EXCEEDS SENSOR RANGE', 'MEMBRANE STABILITY: 94%', 'NOTE: The Source remembers.'] }
};

// ===== CREATURE PROFILES =====
const PROFILES = [
  { name: 'Fugu', type: 'Type 1', classification: 'Hyper-alert Sprinter', firstSighting: 'September 3, 2024', height: '22cm (variable)', behavior: 'Explosive speed, then sudden tender stillness at beauty.', dangerLevel: 'Minimal', notes: 'First to move. First to feel.' },
  { name: 'MrQ', type: 'Type 2', classification: 'Explosive Cheerleader', firstSighting: 'November 19, 2024', height: '20cm', behavior: 'Theatrical fake intimidation. Everything is a performance.', dangerLevel: 'Minimal', notes: 'Believes he is terrifying. Has never terrified anyone.' },
  { name: 'Groovix', type: 'Type 3', classification: 'Clumsy Dancing Giant', firstSighting: 'October 25, 2024', height: '18cm (tallest)', behavior: 'Involuntary rhythm. Tail causes accidental destruction.', dangerLevel: 'Moderate — structural damage', notes: 'Never decides to dance. Movement happens to him.' },
  { name: 'Muncha', type: 'Type 4', classification: 'Anxiety Eater', firstSighting: 'September 12, 2024', height: '16cm', behavior: 'Devours emotional heaviness. Inflates, deflates. Mouth is 70% of body.', dangerLevel: 'None', notes: 'Pure enthusiasm, zero restraint.' }
];

// ===== POST-IT IMAGE ASSETS =====
const POSTIT_IMAGES = [
  'postit-1.png', 'postit-2.png', 'postit-3.png', 'postit-4.png',
  'postit-5.png', 'postit-6.png', 'postit-7.png', 'postit-8.png',
  'postit-9.png', 'postit-10.png', 'postit-11.png', 'postit-12.png',
  'postit-13.png', 'postit-14.png', 'postit-15.png', 'postit-16.png'
];
